//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from D:/GitHub/Open-SCPI-Protocol-Emulator/Source/ProtocolParser/Keysight34465A/Keysight34465ASCPI.g4 by ANTLR 4.13.1

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace ProtocolParser.Keysight34465A {
using System;
using System.IO;
using System.Text;
using System.Diagnostics;
using System.Collections.Generic;
using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.1")]
[System.CLSCompliant(false)]
public partial class Keysight34465ASCPIParser : Parser {
	protected static DFA[] decisionToDFA;
	protected static PredictionContextCache sharedContextCache = new PredictionContextCache();
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, ConfigureVoltage=5, ConfigureCurrent=6, 
		MeasureCurrent=7, MeasureVoltage=8, DisplayText=9, DisplayTextClear=10, 
		SenseVoltageImpedance=11, AC=12, DC=13, AUTO=14, MIN=15, MAX=16, DEF=17, 
		Space=18, CommaSeparator=19, QuestionMark=20, AutoTRUE=21, AutoFALSE=22, 
		Number=23, QuotedString=24;
	public const int
		RULE_command = 0, RULE_identificationQuery = 1, RULE_readQuery = 2, RULE_abortCommand = 3, 
		RULE_configureCurrentCommand = 4, RULE_configureVoltageCommand = 5, RULE_measureCurrentQuery = 6, 
		RULE_measureVoltageQuery = 7, RULE_displayTextCommand = 8, RULE_displayTextClearCommand = 9, 
		RULE_senseVoltageImpedanceCommand = 10, RULE_currentParameters = 11, RULE_voltageParameters = 12;
	public static readonly string[] ruleNames = {
		"command", "identificationQuery", "readQuery", "abortCommand", "configureCurrentCommand", 
		"configureVoltageCommand", "measureCurrentQuery", "measureVoltageQuery", 
		"displayTextCommand", "displayTextClearCommand", "senseVoltageImpedanceCommand", 
		"currentParameters", "voltageParameters"
	};

	private static readonly string[] _LiteralNames = {
		null, "'*IDN?'", "'READ?'", "'ABOR'", "'ABORt'", null, null, null, null, 
		null, null, null, "'AC'", "'DC'", "'AUTO'", "'MIN'", "'MAX'", "'DEF'", 
		null, null, "'?'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, "ConfigureVoltage", "ConfigureCurrent", 
		"MeasureCurrent", "MeasureVoltage", "DisplayText", "DisplayTextClear", 
		"SenseVoltageImpedance", "AC", "DC", "AUTO", "MIN", "MAX", "DEF", "Space", 
		"CommaSeparator", "QuestionMark", "AutoTRUE", "AutoFALSE", "Number", "QuotedString"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "Keysight34465ASCPI.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override int[] SerializedAtn { get { return _serializedATN; } }

	static Keysight34465ASCPIParser() {
		decisionToDFA = new DFA[_ATN.NumberOfDecisions];
		for (int i = 0; i < _ATN.NumberOfDecisions; i++) {
			decisionToDFA[i] = new DFA(_ATN.GetDecisionState(i), i);
		}
	}

		public Keysight34465ASCPIParser(ITokenStream input) : this(input, Console.Out, Console.Error) { }

		public Keysight34465ASCPIParser(ITokenStream input, TextWriter output, TextWriter errorOutput)
		: base(input, output, errorOutput)
	{
		Interpreter = new ParserATNSimulator(this, _ATN, decisionToDFA, sharedContextCache);
	}

	public partial class CommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public IdentificationQueryContext identificationQuery() {
			return GetRuleContext<IdentificationQueryContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Eof() { return GetToken(Keysight34465ASCPIParser.Eof, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ReadQueryContext readQuery() {
			return GetRuleContext<ReadQueryContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public AbortCommandContext abortCommand() {
			return GetRuleContext<AbortCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConfigureCurrentCommandContext configureCurrentCommand() {
			return GetRuleContext<ConfigureCurrentCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MeasureCurrentQueryContext measureCurrentQuery() {
			return GetRuleContext<MeasureCurrentQueryContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ConfigureVoltageCommandContext configureVoltageCommand() {
			return GetRuleContext<ConfigureVoltageCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public MeasureVoltageQueryContext measureVoltageQuery() {
			return GetRuleContext<MeasureVoltageQueryContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DisplayTextCommandContext displayTextCommand() {
			return GetRuleContext<DisplayTextCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public DisplayTextClearCommandContext displayTextClearCommand() {
			return GetRuleContext<DisplayTextClearCommandContext>(0);
		}
		[System.Diagnostics.DebuggerNonUserCode] public SenseVoltageImpedanceCommandContext senseVoltageImpedanceCommand() {
			return GetRuleContext<SenseVoltageImpedanceCommandContext>(0);
		}
		public CommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_command; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CommandContext command() {
		CommandContext _localctx = new CommandContext(Context, State);
		EnterRule(_localctx, 0, RULE_command);
		try {
			State = 56;
			ErrorHandler.Sync(this);
			switch (TokenStream.LA(1)) {
			case T__0:
				EnterOuterAlt(_localctx, 1);
				{
				State = 26;
				identificationQuery();
				State = 27;
				Match(Eof);
				}
				break;
			case T__1:
				EnterOuterAlt(_localctx, 2);
				{
				State = 29;
				readQuery();
				State = 30;
				Match(Eof);
				}
				break;
			case T__2:
			case T__3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 32;
				abortCommand();
				State = 33;
				Match(Eof);
				}
				break;
			case ConfigureCurrent:
				EnterOuterAlt(_localctx, 4);
				{
				State = 35;
				configureCurrentCommand();
				State = 36;
				Match(Eof);
				}
				break;
			case MeasureCurrent:
				EnterOuterAlt(_localctx, 5);
				{
				State = 38;
				measureCurrentQuery();
				State = 39;
				Match(Eof);
				}
				break;
			case ConfigureVoltage:
				EnterOuterAlt(_localctx, 6);
				{
				State = 41;
				configureVoltageCommand();
				State = 42;
				Match(Eof);
				}
				break;
			case MeasureVoltage:
				EnterOuterAlt(_localctx, 7);
				{
				State = 44;
				measureVoltageQuery();
				State = 45;
				Match(Eof);
				}
				break;
			case DisplayText:
				EnterOuterAlt(_localctx, 8);
				{
				State = 47;
				displayTextCommand();
				State = 48;
				Match(Eof);
				}
				break;
			case DisplayTextClear:
				EnterOuterAlt(_localctx, 9);
				{
				State = 50;
				displayTextClearCommand();
				State = 51;
				Match(Eof);
				}
				break;
			case SenseVoltageImpedance:
				EnterOuterAlt(_localctx, 10);
				{
				State = 53;
				senseVoltageImpedanceCommand();
				State = 54;
				Match(Eof);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdentificationQueryContext : ParserRuleContext {
		public IdentificationQueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_identificationQuery; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitIdentificationQuery(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdentificationQueryContext identificationQuery() {
		IdentificationQueryContext _localctx = new IdentificationQueryContext(Context, State);
		EnterRule(_localctx, 2, RULE_identificationQuery);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 58;
			Match(T__0);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ReadQueryContext : ParserRuleContext {
		public ReadQueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_readQuery; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitReadQuery(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ReadQueryContext readQuery() {
		ReadQueryContext _localctx = new ReadQueryContext(Context, State);
		EnterRule(_localctx, 4, RULE_readQuery);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 60;
			Match(T__1);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AbortCommandContext : ParserRuleContext {
		public AbortCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_abortCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAbortCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AbortCommandContext abortCommand() {
		AbortCommandContext _localctx = new AbortCommandContext(Context, State);
		EnterRule(_localctx, 6, RULE_abortCommand);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 62;
			_la = TokenStream.LA(1);
			if ( !(_la==T__2 || _la==T__3) ) {
			ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConfigureCurrentCommandContext : ParserRuleContext {
		public IToken electricityType;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ConfigureCurrent() { return GetToken(Keysight34465ASCPIParser.ConfigureCurrent, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AC() { return GetToken(Keysight34465ASCPIParser.AC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DC() { return GetToken(Keysight34465ASCPIParser.DC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Space() { return GetToken(Keysight34465ASCPIParser.Space, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CurrentParametersContext currentParameters() {
			return GetRuleContext<CurrentParametersContext>(0);
		}
		public ConfigureCurrentCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_configureCurrentCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConfigureCurrentCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConfigureCurrentCommandContext configureCurrentCommand() {
		ConfigureCurrentCommandContext _localctx = new ConfigureCurrentCommandContext(Context, State);
		EnterRule(_localctx, 8, RULE_configureCurrentCommand);
		int _la;
		try {
			State = 70;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,1,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 64;
				Match(ConfigureCurrent);
				State = 65;
				_localctx.electricityType = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==AC || _la==DC) ) {
					_localctx.electricityType = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 66;
				Match(ConfigureCurrent);
				State = 67;
				_localctx.electricityType = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==AC || _la==DC) ) {
					_localctx.electricityType = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 68;
				Match(Space);
				State = 69;
				currentParameters();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ConfigureVoltageCommandContext : ParserRuleContext {
		public IToken electricityType;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode ConfigureVoltage() { return GetToken(Keysight34465ASCPIParser.ConfigureVoltage, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AC() { return GetToken(Keysight34465ASCPIParser.AC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DC() { return GetToken(Keysight34465ASCPIParser.DC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Space() { return GetToken(Keysight34465ASCPIParser.Space, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VoltageParametersContext voltageParameters() {
			return GetRuleContext<VoltageParametersContext>(0);
		}
		public ConfigureVoltageCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_configureVoltageCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitConfigureVoltageCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ConfigureVoltageCommandContext configureVoltageCommand() {
		ConfigureVoltageCommandContext _localctx = new ConfigureVoltageCommandContext(Context, State);
		EnterRule(_localctx, 10, RULE_configureVoltageCommand);
		int _la;
		try {
			State = 78;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,2,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 72;
				Match(ConfigureVoltage);
				State = 73;
				_localctx.electricityType = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==AC || _la==DC) ) {
					_localctx.electricityType = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 74;
				Match(ConfigureVoltage);
				State = 75;
				_localctx.electricityType = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==AC || _la==DC) ) {
					_localctx.electricityType = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 76;
				Match(Space);
				State = 77;
				voltageParameters();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MeasureCurrentQueryContext : ParserRuleContext {
		public IToken electricityType;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MeasureCurrent() { return GetToken(Keysight34465ASCPIParser.MeasureCurrent, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QuestionMark() { return GetToken(Keysight34465ASCPIParser.QuestionMark, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AC() { return GetToken(Keysight34465ASCPIParser.AC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DC() { return GetToken(Keysight34465ASCPIParser.DC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Space() { return GetToken(Keysight34465ASCPIParser.Space, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public CurrentParametersContext currentParameters() {
			return GetRuleContext<CurrentParametersContext>(0);
		}
		public MeasureCurrentQueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_measureCurrentQuery; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMeasureCurrentQuery(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MeasureCurrentQueryContext measureCurrentQuery() {
		MeasureCurrentQueryContext _localctx = new MeasureCurrentQueryContext(Context, State);
		EnterRule(_localctx, 12, RULE_measureCurrentQuery);
		int _la;
		try {
			State = 88;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,3,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 80;
				Match(MeasureCurrent);
				State = 81;
				_localctx.electricityType = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==AC || _la==DC) ) {
					_localctx.electricityType = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 82;
				Match(QuestionMark);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 83;
				Match(MeasureCurrent);
				State = 84;
				_localctx.electricityType = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==AC || _la==DC) ) {
					_localctx.electricityType = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 85;
				Match(QuestionMark);
				State = 86;
				Match(Space);
				State = 87;
				currentParameters();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MeasureVoltageQueryContext : ParserRuleContext {
		public IToken electricityType;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MeasureVoltage() { return GetToken(Keysight34465ASCPIParser.MeasureVoltage, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QuestionMark() { return GetToken(Keysight34465ASCPIParser.QuestionMark, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AC() { return GetToken(Keysight34465ASCPIParser.AC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DC() { return GetToken(Keysight34465ASCPIParser.DC, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Space() { return GetToken(Keysight34465ASCPIParser.Space, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public VoltageParametersContext voltageParameters() {
			return GetRuleContext<VoltageParametersContext>(0);
		}
		public MeasureVoltageQueryContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_measureVoltageQuery; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMeasureVoltageQuery(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MeasureVoltageQueryContext measureVoltageQuery() {
		MeasureVoltageQueryContext _localctx = new MeasureVoltageQueryContext(Context, State);
		EnterRule(_localctx, 14, RULE_measureVoltageQuery);
		int _la;
		try {
			State = 98;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,4,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 90;
				Match(MeasureVoltage);
				State = 91;
				_localctx.electricityType = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==AC || _la==DC) ) {
					_localctx.electricityType = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 92;
				Match(QuestionMark);
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 93;
				Match(MeasureVoltage);
				State = 94;
				_localctx.electricityType = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !(_la==AC || _la==DC) ) {
					_localctx.electricityType = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 95;
				Match(QuestionMark);
				State = 96;
				Match(Space);
				State = 97;
				voltageParameters();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DisplayTextCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DisplayText() { return GetToken(Keysight34465ASCPIParser.DisplayText, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Space() { return GetToken(Keysight34465ASCPIParser.Space, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode QuotedString() { return GetToken(Keysight34465ASCPIParser.QuotedString, 0); }
		public DisplayTextCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_displayTextCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDisplayTextCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DisplayTextCommandContext displayTextCommand() {
		DisplayTextCommandContext _localctx = new DisplayTextCommandContext(Context, State);
		EnterRule(_localctx, 16, RULE_displayTextCommand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 100;
			Match(DisplayText);
			State = 101;
			Match(Space);
			State = 102;
			Match(QuotedString);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DisplayTextClearCommandContext : ParserRuleContext {
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DisplayTextClear() { return GetToken(Keysight34465ASCPIParser.DisplayTextClear, 0); }
		public DisplayTextClearCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_displayTextClearCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDisplayTextClearCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DisplayTextClearCommandContext displayTextClearCommand() {
		DisplayTextClearCommandContext _localctx = new DisplayTextClearCommandContext(Context, State);
		EnterRule(_localctx, 18, RULE_displayTextClearCommand);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 104;
			Match(DisplayTextClear);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SenseVoltageImpedanceCommandContext : ParserRuleContext {
		public IToken @bool;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode SenseVoltageImpedance() { return GetToken(Keysight34465ASCPIParser.SenseVoltageImpedance, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AutoTRUE() { return GetToken(Keysight34465ASCPIParser.AutoTRUE, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AutoFALSE() { return GetToken(Keysight34465ASCPIParser.AutoFALSE, 0); }
		public SenseVoltageImpedanceCommandContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_senseVoltageImpedanceCommand; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSenseVoltageImpedanceCommand(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SenseVoltageImpedanceCommandContext senseVoltageImpedanceCommand() {
		SenseVoltageImpedanceCommandContext _localctx = new SenseVoltageImpedanceCommandContext(Context, State);
		EnterRule(_localctx, 20, RULE_senseVoltageImpedanceCommand);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106;
			Match(SenseVoltageImpedance);
			State = 107;
			_localctx.@bool = TokenStream.LT(1);
			_la = TokenStream.LA(1);
			if ( !(_la==AutoTRUE || _la==AutoFALSE) ) {
				_localctx.@bool = ErrorHandler.RecoverInline(this);
			}
			else {
				ErrorHandler.ReportMatch(this);
			    Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CurrentParametersContext : ParserRuleContext {
		public IToken range;
		public IToken resolution;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Number() { return GetTokens(Keysight34465ASCPIParser.Number); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number(int i) {
			return GetToken(Keysight34465ASCPIParser.Number, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AUTO() { return GetToken(Keysight34465ASCPIParser.AUTO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MIN() { return GetTokens(Keysight34465ASCPIParser.MIN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MIN(int i) {
			return GetToken(Keysight34465ASCPIParser.MIN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MAX() { return GetTokens(Keysight34465ASCPIParser.MAX); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MAX(int i) {
			return GetToken(Keysight34465ASCPIParser.MAX, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DEF() { return GetTokens(Keysight34465ASCPIParser.DEF); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEF(int i) {
			return GetToken(Keysight34465ASCPIParser.DEF, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CommaSeparator() { return GetToken(Keysight34465ASCPIParser.CommaSeparator, 0); }
		public CurrentParametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_currentParameters; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCurrentParameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CurrentParametersContext currentParameters() {
		CurrentParametersContext _localctx = new CurrentParametersContext(Context, State);
		EnterRule(_localctx, 22, RULE_currentParameters);
		int _la;
		try {
			State = 113;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,5,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 109;
				_localctx.range = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 8634368L) != 0)) ) {
					_localctx.range = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 110;
				_localctx.range = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 8634368L) != 0)) ) {
					_localctx.range = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 111;
				Match(CommaSeparator);
				State = 112;
				_localctx.resolution = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 8617984L) != 0)) ) {
					_localctx.resolution = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class VoltageParametersContext : ParserRuleContext {
		public IToken range;
		public IToken resolution;
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] Number() { return GetTokens(Keysight34465ASCPIParser.Number); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode Number(int i) {
			return GetToken(Keysight34465ASCPIParser.Number, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode AUTO() { return GetToken(Keysight34465ASCPIParser.AUTO, 0); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MIN() { return GetTokens(Keysight34465ASCPIParser.MIN); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MIN(int i) {
			return GetToken(Keysight34465ASCPIParser.MIN, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] MAX() { return GetTokens(Keysight34465ASCPIParser.MAX); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode MAX(int i) {
			return GetToken(Keysight34465ASCPIParser.MAX, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode[] DEF() { return GetTokens(Keysight34465ASCPIParser.DEF); }
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode DEF(int i) {
			return GetToken(Keysight34465ASCPIParser.DEF, i);
		}
		[System.Diagnostics.DebuggerNonUserCode] public ITerminalNode CommaSeparator() { return GetToken(Keysight34465ASCPIParser.CommaSeparator, 0); }
		public VoltageParametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_voltageParameters; } }
		[System.Diagnostics.DebuggerNonUserCode]
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			IKeysight34465ASCPIVisitor<TResult> typedVisitor = visitor as IKeysight34465ASCPIVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitVoltageParameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public VoltageParametersContext voltageParameters() {
		VoltageParametersContext _localctx = new VoltageParametersContext(Context, State);
		EnterRule(_localctx, 24, RULE_voltageParameters);
		int _la;
		try {
			State = 119;
			ErrorHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(TokenStream,6,Context) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 115;
				_localctx.range = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 8634368L) != 0)) ) {
					_localctx.range = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 116;
				_localctx.range = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 8634368L) != 0)) ) {
					_localctx.range = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				State = 117;
				Match(CommaSeparator);
				State = 118;
				_localctx.resolution = TokenStream.LT(1);
				_la = TokenStream.LA(1);
				if ( !((((_la) & ~0x3f) == 0 && ((1L << _la) & 8617984L) != 0)) ) {
					_localctx.resolution = ErrorHandler.RecoverInline(this);
				}
				else {
					ErrorHandler.ReportMatch(this);
				    Consume();
				}
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			ErrorHandler.ReportError(this, re);
			ErrorHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	private static int[] _serializedATN = {
		4,1,24,122,2,0,7,0,2,1,7,1,2,2,7,2,2,3,7,3,2,4,7,4,2,5,7,5,2,6,7,6,2,7,
		7,7,2,8,7,8,2,9,7,9,2,10,7,10,2,11,7,11,2,12,7,12,1,0,1,0,1,0,1,0,1,0,
		1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,1,
		0,1,0,1,0,1,0,1,0,1,0,1,0,1,0,3,0,57,8,0,1,1,1,1,1,2,1,2,1,3,1,3,1,4,1,
		4,1,4,1,4,1,4,1,4,3,4,71,8,4,1,5,1,5,1,5,1,5,1,5,1,5,3,5,79,8,5,1,6,1,
		6,1,6,1,6,1,6,1,6,1,6,1,6,3,6,89,8,6,1,7,1,7,1,7,1,7,1,7,1,7,1,7,1,7,3,
		7,99,8,7,1,8,1,8,1,8,1,8,1,9,1,9,1,10,1,10,1,10,1,11,1,11,1,11,1,11,3,
		11,114,8,11,1,12,1,12,1,12,1,12,3,12,120,8,12,1,12,0,0,13,0,2,4,6,8,10,
		12,14,16,18,20,22,24,0,5,1,0,3,4,1,0,12,13,1,0,21,22,2,0,14,17,23,23,2,
		0,15,17,23,23,123,0,56,1,0,0,0,2,58,1,0,0,0,4,60,1,0,0,0,6,62,1,0,0,0,
		8,70,1,0,0,0,10,78,1,0,0,0,12,88,1,0,0,0,14,98,1,0,0,0,16,100,1,0,0,0,
		18,104,1,0,0,0,20,106,1,0,0,0,22,113,1,0,0,0,24,119,1,0,0,0,26,27,3,2,
		1,0,27,28,5,0,0,1,28,57,1,0,0,0,29,30,3,4,2,0,30,31,5,0,0,1,31,57,1,0,
		0,0,32,33,3,6,3,0,33,34,5,0,0,1,34,57,1,0,0,0,35,36,3,8,4,0,36,37,5,0,
		0,1,37,57,1,0,0,0,38,39,3,12,6,0,39,40,5,0,0,1,40,57,1,0,0,0,41,42,3,10,
		5,0,42,43,5,0,0,1,43,57,1,0,0,0,44,45,3,14,7,0,45,46,5,0,0,1,46,57,1,0,
		0,0,47,48,3,16,8,0,48,49,5,0,0,1,49,57,1,0,0,0,50,51,3,18,9,0,51,52,5,
		0,0,1,52,57,1,0,0,0,53,54,3,20,10,0,54,55,5,0,0,1,55,57,1,0,0,0,56,26,
		1,0,0,0,56,29,1,0,0,0,56,32,1,0,0,0,56,35,1,0,0,0,56,38,1,0,0,0,56,41,
		1,0,0,0,56,44,1,0,0,0,56,47,1,0,0,0,56,50,1,0,0,0,56,53,1,0,0,0,57,1,1,
		0,0,0,58,59,5,1,0,0,59,3,1,0,0,0,60,61,5,2,0,0,61,5,1,0,0,0,62,63,7,0,
		0,0,63,7,1,0,0,0,64,65,5,6,0,0,65,71,7,1,0,0,66,67,5,6,0,0,67,68,7,1,0,
		0,68,69,5,18,0,0,69,71,3,22,11,0,70,64,1,0,0,0,70,66,1,0,0,0,71,9,1,0,
		0,0,72,73,5,5,0,0,73,79,7,1,0,0,74,75,5,5,0,0,75,76,7,1,0,0,76,77,5,18,
		0,0,77,79,3,24,12,0,78,72,1,0,0,0,78,74,1,0,0,0,79,11,1,0,0,0,80,81,5,
		7,0,0,81,82,7,1,0,0,82,89,5,20,0,0,83,84,5,7,0,0,84,85,7,1,0,0,85,86,5,
		20,0,0,86,87,5,18,0,0,87,89,3,22,11,0,88,80,1,0,0,0,88,83,1,0,0,0,89,13,
		1,0,0,0,90,91,5,8,0,0,91,92,7,1,0,0,92,99,5,20,0,0,93,94,5,8,0,0,94,95,
		7,1,0,0,95,96,5,20,0,0,96,97,5,18,0,0,97,99,3,24,12,0,98,90,1,0,0,0,98,
		93,1,0,0,0,99,15,1,0,0,0,100,101,5,9,0,0,101,102,5,18,0,0,102,103,5,24,
		0,0,103,17,1,0,0,0,104,105,5,10,0,0,105,19,1,0,0,0,106,107,5,11,0,0,107,
		108,7,2,0,0,108,21,1,0,0,0,109,114,7,3,0,0,110,111,7,3,0,0,111,112,5,19,
		0,0,112,114,7,4,0,0,113,109,1,0,0,0,113,110,1,0,0,0,114,23,1,0,0,0,115,
		120,7,3,0,0,116,117,7,3,0,0,117,118,5,19,0,0,118,120,7,4,0,0,119,115,1,
		0,0,0,119,116,1,0,0,0,120,25,1,0,0,0,7,56,70,78,88,98,113,119
	};

	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN);


}
} // namespace ProtocolParser.Keysight34465A
